/**
 * a class that holds the possible location types
 */
public enum LocationType {
    OUTSIDE, LIVINGROOM, BEDROOM, KITCHEN, GARAGE, OFFICE, INSIDE, CURRENT , LIVINGROOM_STOOP,BEDROOM_STOOP,KITCHEN_STOOP,GARAGE_STOOP,OFFICE_STOOP
}
