/**
 * a class that holds the possible location types
 */
public enum LocationType {
    OUTSIDE, LIVINGROOM, BEDROOM, KITCHEN, GARAGE, OFFICE, INSIDE, CURRENT , LIVINGROOMSTOOP,BEDROOMSTOOP,KITCHENSTOOP,GARAGESTOOP,OFFICESTOOP
}
